ALTER SEQUENCE animal_id_seq RESTART WITH 1;
ALTER SEQUENCE endereco_id_seq RESTART WITH 1;
ALTER SEQUENCE internamento_id_seq RESTART WITH 1;
ALTER SEQUENCE medicacao_id_seq RESTART WITH 1;
ALTER SEQUENCE monitoramento_id_seq RESTART WITH 1;
ALTER SEQUENCE raca_id_seq RESTART WITH 1;
ALTER SEQUENCE usomedicacao_id_seq RESTART WITH 1;
ALTER SEQUENCE usuario_id_seq RESTART WITH 1;

CREATE EXTENSION pgcrypto;